Repository esulu/COMP3005-Project, pull requests merged in 2021-11, with the labels that each got.

#3 Populate db
  README.md
  SQL/populate.ddl
  scripts/.gitignore
  scripts/createDDL.py
Labels: database

#24 added endpoints for authors, books, book/isbn, added interface for th…
  SQL/DDL.sql
  SQL/Queries/authors.sql
  SQL/Queries/book.sql
  SQL/Queries/books.sql
  server/source/db.ts
  server/source/server.ts
Labels: database, back-end

#27 Bookcomponent
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Book/Book.tsx
  client/src/components/Book/BookStore.css
  client/src/components/Book/BookStore.tsx
  client/src/components/index.tsx
  client/src/pages/Store/Store.tsx
  server/package-lock.json
  server/source/db.ts
  server/source/server.ts
Labels: database, front-end, back-end

#28 Booksearch
  server/source/db.ts
  server/source/server.ts
Labels: database, back-end

#31 added login page and authentication
  README.md
  SQL/Queries/login.sql
  SQL/populate.sql
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Auth/PrivateRoute.tsx
  client/src/components/Auth/UseToken.tsx
  client/src/components/Book/BookStore.tsx
  client/src/components/Fragments/Header.tsx
  client/src/components/Navigation/NavBar.tsx
  client/src/components/index.tsx
  client/src/pages/Cart/Cart.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Orders/Orders.tsx
  client/src/pages/Store/Store.tsx
  client/src/pages/index.tsx
  server/source/db.ts
  server/source/server.ts
Labels: database, front-end, back-end

#35 added backend support for specific book
  SQL/Queries/book.sql
  server/source/server.ts
Labels: database, back-end

#37 Dbfix
  SQL/DDL.sql
  SQL/populate.sql
  client/src/components/Book/BookStore.tsx
  server/source/server.ts
Labels: database, back-end

#38 Search bar implementation
  SQL/Queries/getAuthors.sql
  SQL/Queries/getGenres.sql
  SQL/Queries/getIsbns.sql
  SQL/Queries/getTitles.sql
  client/src/components/Book/BookStore.css
  client/src/components/Book/BookStore.tsx
  client/src/components/Fragments/SearchBar.tsx
  client/src/components/index.tsx
  client/src/pages/Store/Store.tsx
  server/source/server.ts
Labels: database, front-end, back-end

#41 6 bookview
  client/src/components/Book/Book.tsx
  client/src/components/Book/BookStore.css
  client/src/components/Book/BookView.tsx
  client/src/components/Navigation/NavBar.tsx
Labels: front-end, back-end

#42 Checkoutprocedure
  SQL/DDL.sql
  SQL/Queries/getNumberOfBooksInCart.sql
  SQL/Queries/insertCart.sql
  SQL/Queries/insertOrder.sql
  SQL/Queries/insertShipping.sql
  SQL/Queries/setUserCart.sql
  SQL/Queries/userCarts.sql
  SQL/Queries/verifyUser.sql
  SQL/Queries/warehouses.sql
  SQL/populate.sql
  client/src/components/CheckoutModal/CheckoutAlert.tsx
  client/src/components/CheckoutModal/CheckoutModal.tsx
  client/src/components/CheckoutModal/CheckoutView.tsx
  client/src/components/index.tsx
  client/src/pages/Cart/Cart.tsx
  server/package-lock.json
  server/package.json
  server/source/db.ts
  server/source/server.ts
Labels: database, front-end, back-end

#46 Ownertabs
  SQL/Queries/login.sql
  client/src/App.tsx
  client/src/components/Auth/UseToken.tsx
  client/src/components/CheckoutModal/CheckoutAlert.tsx
  client/src/components/Navigation/NavBar.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/ModifyBookstore/ModifyBookstore.tsx
  client/src/pages/NoMatch/NoMatch.tsx
  client/src/pages/Statistics/Statistics.tsx
  client/src/pages/index.tsx
  server/source/server.ts
Labels: front-end

#48 40 update cart
  SQL/Queries/getCart.sql
  SQL/Queries/getCartID.sql
  SQL/Queries/removeFromCart.sql
  client/src/components/Book/Book.tsx
  client/src/components/Book/BookCartView.tsx
  client/src/components/Book/BookStore.tsx
  client/src/components/Book/BookView.tsx
  client/src/components/CheckoutModal/CheckoutAlert.tsx
  client/src/components/CheckoutModal/CheckoutModal.tsx
  client/src/components/CheckoutModal/CheckoutView.tsx
  client/src/components/index.tsx
  client/src/pages/Cart/Cart.tsx
  server/source/server.ts
Labels: database, front-end, back-end

#47 Tracking view
  SQL/Queries/orderInfo.sql
  client/src/pages/Orders/OrderTable.tsx
  client/src/pages/Orders/Orders.tsx
  server/source/server.ts
Labels: front-end, back-end

#50 added all views
  SQL/views.sql
Labels: database

#54 View statistics
  SQL/Queries/getBookSalesPerGenre.sql
  SQL/Queries/getSalesExpenditure.sql
  SQL/Queries/getSalesPerAuthor.sql
  SQL/views.sql
  client/package-lock.json
  client/package.json
  client/src/pages/Statistics/Statistics.tsx
  client/src/pages/Statistics/StatisticsSalesPerGenre.tsx
  client/src/pages/Statistics/StatisticsScatterChart.tsx
  server/package-lock.json
  server/package.json
  server/source/server.ts
Labels: front-end

#56 added sql for previous month books
  SQL/Queries/previousMonthBookSale.sql
Labels: database
